export const dictionary_list = {
  facile: ["CHAT", "CHIEN", "TABLE", "CHAISE", "LIVRE", "POMME", "MAISON", "PORTE",
  "ROUTE", "TRAIN", "AVION", "PLAGE", "SOLEIL", "LUNE", "EAU", "FEU",
  "TERRE", "VENT", "NEIGE", "ARBRE", "FLEUR", "HERBE", "FRUIT", "SUCRE",
  "SEL", "PAIN", "FROMAGE", "BEURRE", "RIZ", "LAIT", "CAFE", "THE",
  "VERRE", "BOL", "ASSIETTE", "FOUR", "LIT", "MUR", "SOL", "TOIT",
  "VILLE", "PAYS", "MONDE", "AMI", "FAMILLE", "ENFANT", "PARENT"], 

  moyen: ["ORAGE", "NUAGE", "TEMPETE", "BRISE", "CLAIR", "OMBRE", "REFLET",
  "VOYAGE", "BAGAGE", "VALISE", "HORIZON", "SILENCE", "SECRET",
  "ESPOIR", "SOUVENIR", "MYSTÈRE", "HASARD", "DESTIN", "ÉNERGIE",
  "MOTEUR", "PUZZLE", "CLAVIER", "ÉCRAN", "SIGNAL", "RESEAU",
  "SYSTEME", "PROJET", "CONCEPT", "IDEE", "SCHEMA", "STRUCTURE",
  "ANALYSE", "LOGIQUE", "DONNEE", "VARIABLE", "FONCTION",
  "ALGORITHME", "MÉMOIRE", "PROCESSUS"], 
  
  difficile: ["ABYSSAL", "OPAQUE", "EQUIVOQUE", "ZEPHYR", "XYLOPHONE",
  "KIOSQUE", "WHISKY", "YAK", "FJORD", "SPHINX",
  "QUARTZ", "ZYGOTE", "MYTHIQUE", "PARADOXE",
  "AXIOME", "BARYON", "CRYPTE", "DYNAMIQUE",
  "EXIGU", "FAUVE", "GLACIAL", "HIATUS",
  "INCISIF", "JONCTION", "KAPUTT", "LABYRINTHE",
  "MOSAIQUE", "NEBULEUX", "OBLIQUE", "PYROMANE",
  "OLYMPIQUE", "QUINTESSENCE", "RHIZOME", "SERENDIPITE",
  "TACTIQUE", "UBIQUITE", "VORTEX", "WATT",
  "XENON", "YACHT", "ZODIAC"]
  };